[package]
name = "allinone"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

inkstone-admin-core = { path = "../admin_core" }
inkstone-app = { path = "../app" }
inkstone-infra = { path = "../infra" }
inkstone-runtime = { path = "../runtime" }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
